### ISSUE TITLE
ERCnet throws an No File / Directory error when run with the following command. 

### ISSUE THREAD

**Issue by tgattsIV** [EvanForsythe/ERCnet#21]
Command :  python Phylogenomics.py -j newTestTest -t 50 -o /scratch/summit/zypher@colostate.edu/ERC/Orthofinder/III/OrthoFinder/Results_Mar22_1/ -p 3  -r 10 -x /projects/zypher@colostate.edu/software/anaconda/envs/ERCnet_py3/bin/

Program Output : 

Finding the Orthofinder HOG file to be used to designate ingroup subtrees

--Node (-n) not defined. Choosing N1.tsv HOF file by default
Note that N1.tsv is only appropriate if your species tree contains a single outgroup species.

All output files will be written to OUT_newTestTest/

HOG file for selected node located at:
/scratch/summit/zypher@colostate.edu/ERC/Orthofinder/III/OrthoFinder/Results_Mar22_1/Phylogenetic_Hierarchical_Orthogroups/N1.tsv

Attempting to create Species_mapping.csv in output directory.
The following species identifiers will be used:
['Acom', 'Aoff', 'Atha', 'Bdis', 'Dala', 'Hvul', 'Macu', 'Msin', 'Osat', 'Otho', 'Phal', 'Pvir', 'Sbic', 'Spol', 'Svir', 'Taes', 'Zmar', 'Zmay']
These should match the column headers in the HOG file (e.g. N1.tsv) and the tip labels in the species tree

The following species identifiers will be used:
['Acom', 'Aoff', 'Atha', 'Bdis', 'Dala', 'Hvul', 'Macu', 'Msin', 'Osat', 'Otho', 'Phal', 'Pvir', 'Sbic', 'Spol', 'Svir', 'Taes', 'Zmar', 'Zmay']
These should be present in the sequence IDs in alignments etc...

Sequence counts per species dataframe successfully generated

Writing sequence counts per species table to "Seq_counts_per_species.csv"

--MaxP_val set to 3 and --MinR_val set to 10
Filtering data....
Dataset filtering successful

Filtered list of gene families successfully generated.

Filtered dataset contains 50 genes.

Csv file written to Filtered_genefam_dataset.csv

Fasta files will be written to HOG_seqs/

Traceback (most recent call last):
  File "Phylogenomics.py", line 282, in <module>
    OG_dict = SeqIO.to_dict(SeqIO.parse(str(OGseqdir + OGtemp +'.fa'), 'fasta'))
  File "/projects/zypher@colostate.edu/software/anaconda/envs/ERCnet_py3/lib/python3.7/site-packages/Bio/SeqIO/__init__.py", line 605, in parse
    return iterator_generator(handle)
  File "/projects/zypher@colostate.edu/software/anaconda/envs/ERCnet_py3/lib/python3.7/site-packages/Bio/SeqIO/FastaIO.py", line 183, in __init__
    super().__init__(source, mode="t", fmt="Fasta")
  File "/projects/zypher@colostate.edu/software/anaconda/envs/ERCnet_py3/lib/python3.7/site-packages/Bio/SeqIO/Interfaces.py", line 48, in __init__
    self.stream = open(source, "r" + mode)
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/summit/zypher@colostate.edu/ERC/Orthofinder/III/OrthoFinder/Results_Mar22_1/Orthogroup_Sequences/OG0012235.fa'

**Comment by EvanForsythe** [comment]
Hey Tony, it looks like the cause of the issue is that expected input files are missing (the Orthogroup_Sequences/ directory). These were expected to be standard output of Orthofinder so it seems that Orthofinder ran in an unexpected way for you. Could you please check the version of Orthofinder that's installed on the conda environment from which you ran Orthofinder? Monica and I both have Orthofinder v2.5.4 installed and our input contains the expected Orthogroup_Sequences/ directory FYI. To get the version of Orthofinder you can run orthofinder --help once you're in your conda env.

**Comment by tgattsIV** [comment]
Issue was caused by rerunning Orthofinder with a user rooted tree and skipping the BLAST step. This caused the new results Folder to not contain all the required information for ERCnet to function. 

Solution: Copy the Orthologue_Sequences directory from the initial Orthofinder run into the latter results folder.

**Comment by EvanForsythe** [comment]
Glad you figured it out! Fyi, I added a more informative error message in case this type of problem crops up again.
