### ISSUE TITLE
ERCnet fails to complete run successfully. 

### ISSUE THREAD

**Issue by tgattsIV** [EvanForsythe/ERCnet#23]
Error: TypeError '>=' not supported between instance of int and 'NoneType'

![image](https://user-images.githubusercontent.com/82840682/163036771-153abd93-7d97-4cb5-98f4-7ac5014e8ddb.png)

**Comment by EvanForsythe** [comment]
Hi Tony, I just added an update that should fix the problem. Please pull the new version of ERCnet (main branch) and let me know if if fixes the issue. Thanks!

**Comment by tgattsIV** [comment]
![image](https://user-images.githubusercontent.com/82840682/163043774-4fa06b47-60fb-4891-9d1b-607d5bec4734.png)

**Comment by EvanForsythe** [comment]
It looks like the error was stemming from a missing -l argument in your command. I updated Phylogenomics.py to handle missing arguments (where permissible). Thanks for catching this bug! Closing the issue.
