### ISSUE TITLE
Refactor ERC_analyses.py to perform pearson and spearman in one run

### ISSUE THREAD

**Issue by EvanForsythe** [EvanForsythe/ERCnet#72]
-Change ERC_analyses.py so that both pearson and spearman correlation analyses are calculated. This means that the user will no longer need to choose spearman vs pearson, both are calculated automatically. The use will still need to choose R2T versus BXB.

-Change Network_analyses.py to accommodate the new format of the ERC results csv file.

-Change Network_analyses.py so that the user can choose "pearson", "spearman", or "both". If both are selected, the p-value and R2 cutoffs will be applied to both pearson and spearman values. (e.g. retain row if pearson-P<0.05 AND spearman-P<0.05).

**Comment by tgattsIV** [comment]
Should be complete in current iteration of main.
